### ISSUE TITLE
Error: null address reference

### ISSUE THREAD

**Issue by forrestthewoods** [marcoesposito1988/dependency_runner#2]
Hi. I frequently run into issues where DLLs won't load and the issue is missing deps. This tool looked like exactly what I want.

Unfortunately when I try the tool it just says "Error: null address reference" with no additional information. On another DLL it says "Error: address misaligned".

Any thoughts?

**Comment by marcoesposito1988** [comment]
Hi @forrestthewoods,
thanks for the report! Have you already tried the latest release 1.0.0? It should at least give a better error message.
Would it be possible to provide the DLLs for debugging?

**Comment by forrestthewoods** [comment]
Hi. This was with the latest 1.0 release from the releases page. deprun_x86_64-pc-windows-msvc.

Unfortunately the binaries it's failing on are proprietary and I can not share them. :(

**Comment by marcoesposito1988** [comment]
I see. Are they by any chance 32-bit?

**Comment by forrestthewoods** [comment]
Nope. 64-bit across the board. :(

**Comment by marcoesposito1988** [comment]
I added an alternative parser based on [goblin](https://github.com/m4b/goblin), which is supposed to be more robust to this kind of errors.

It is on the [goblin branch](https://github.com/marcoesposito1988/dependency_runner/tree/goblin). Are you familiar with rust, can you build it yourself? Otherwise I can build it locally, if you will trust my binary :)

**Comment by marcoesposito1988** [comment]
The goblin parser is the default since 1.1.0. I am closing this issue, please feel free to reopen it if this issue arises again.
